### ISSUE TITLE
Modifying ace_eval.h to run example code, speed_test, or accuracy_test

### ISSUE THREAD

**Issue by ChrisMc9** [ashelly/ACE_eval#2]
I've been trying to stand up this project. The accuracy and speed tests do not run as-is. 

It seems that to run the example code in accuracy_test or speed_test, a function E() needs to be put into the ace_eval.h file. Adding that and a "compress" function allowed me to compile the project and run it - producing the proper, accurate results. 

Can you confirm the procedure for running the project? I copied E() and compress() from ace_eval_decompress. Doing so, I get some warnings about benign redefinition of type C4142. But hey, accurate results! 

Apologies for not being knowledgeable about this. I am trying to cythonize it and bring it into a language I can work in. Let me know if you'd be interested in having the files included in your project. 

I used this compress function: 
Card compress(Card a){
  a=(a|(a>>1))&0x33333333;
  a=(a|(a>>2))&0x0f0f0f0f;
  a=(a|(a>>4))&0x00ff00ff;
  a=(a|(a>>8))&0x0000ffff;
  return a>>3;
}

**Comment by ashelly** [comment]
I fixed the compiler warning in `ace_eval.h`. 
To build an executable with the accuracy_test use `make test_base` or `make test_decompress` (depending on which optimized version you want: decompress is the fastest so far.)
To build with speed test use `make time_decompress`.

What all those `make <X>_<V>` targets are doing is compiling both `<X>_test.c` and `ace_eval_<V>.c` into the same executable.  The `ace_eval_<V>.c` files contain the `E()` and `compress()` functions you were looking for.

**Comment by ChrisMc9** [comment]
Thanks. Very timely since I was working on this again today. Thanks for explaining the makefile. I'll let you know as I make progress on the bindings.
